### ISSUE TITLE
Sensor fusion null pointer exception

### ISSUE THREAD

**Issue by ameenmaheen** [FinweLtd/orion360-sdk-basic-hello-android#3]
Dear team

I am using the code you have provided in this repository , Sometime when i press back before the video loads i get this exception

`FATAL EXCEPTION: main
                                                                             Process: com.creativeinnovations.mea, PID: 30209
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'fi.finwe.orion360.OrionSensorFusion fi.finwe.orion360.OrionContext.GetSensorFusion()' on a null object reference
                                                                                 at fi.finwe.orion360.OrionSurfaceView.onPrepared(OrionSurfaceView.java:386)
                                                                                 at fi.finwe.orion360.OrionVideoView.onOrionVideoPlayerMessage(OrionVideoView.java:698)
                                                                                 at fi.finwe.orion360.OrionVideoPlayerAsync$UIHandler.handleMessage(OrionVideoPlayerAsync.java:306)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

why is it happening ? I am streaming the video ..

**Comment by trantako** [comment]
Hi,

Initializing an OrionVideoView is an asynchrounous operation. When you set a remote video URI to your OrionVideoView, it will take a while to prepare the video player. This amount of time depends on your network connection and the video file.

If you press Back button at this phase, you will typically navigate away from the player view, which will destroy some resources.

In this case, a callback comes a bit later (when the video player has been prepared) and it results to NullPointerException since some resources have just been destroyed (because you returned from the player by pressing the Back button).

We should probably guard against this situation in Orion360 side (to be fixed in next release). Meanwhile, you may want to capture Back button press and either manually destroy your OrionVideoView or wait until onPrepared() is called before navigating away from the player.

**Comment by ameenmaheen** [comment]
Hi team
Any update on this issue ? have you able to rectify the issue  ? As per your instruction i have implemented logic on the back press . most of the time this is not happening , still 1 or 2 devices are reported with this crash .

**Comment by trantako** [comment]
We have pushed a new release to Bintray. Please change Orion360 SDK version to 1.2.04 in your gradle file, for example: compile 'fi.finwe.orion360:orion360-sdk-basic:1.2.04'

Let's us know if this fixes the issue by replying to this thread. Thanks.

**Comment by ameenmaheen** [comment]
thanks ,i have upgraded to new version , i will close this issue if the problem is fixed

**Comment by ameenmaheen** [comment]
@trantako  hi , after i have updated to the new library the only sensor motion is working on video , i cant touch and change the direction of the video :-(

**Comment by trantako** [comment]
Thank you for reporting this. A small copy-paste bug had slipped in. Fixed in this version:
compile 'fi.finwe.orion360:orion360-sdk-basic:1.2.05'

**Comment by ameenmaheen** [comment]
ok i will compile this version and will update the progress

**Comment by ameenmaheen** [comment]
yes the touch is now working , i will update the issue with sensor fusion(The original bug) soon

**Comment by ameenmaheen** [comment]
nothing popped up so far , i am closing the issue
